import json,xlwt


def readExcel(file):
    with open(file,'r',encoding='utf8') as fr:
        data = json.load(fr) # 用json中的load方法，将json串转换成字典
    return data
def writeM(data):
     # a = readExcel('json')
     a = data
     print(a)
     title = ['ID', 'CARNAME', 'CSZDJ', 'CS', 'JIBIE', 'NYLX', 'SHANGSSJ', 'ZUIDAGL', 'ZUIDANJ', 'FDJ', 'BIANSX', 'CHANGKG', 'CHESJG', 'ZUIGCS', 'GUANGF0_100JS', 'SHIC0_100JS', 'SHIC0_100ZD', 'GONGXBZHYH', 'SHICYH', 'ZHENGCZB', 'CHANGDU', 'KUANDU', 'GAODU', 'ZHOUJU', 'QIANLUNJU', 'HOULUNJU', 'ZUIXLDJX', 'CHEMENSHU', 'ZUOWEISHU', 'YOUXRJ', 'XINGLXRJ', 'ZHENGBZL', 'FADJXH', 'PAILIANGML', 'PAILIANGL', 'JINQXS', 'QIGPLXS', 'QIGANGSHU', 'MEIGQMS', 'YANSUOBI', 'PEIQJG', 'GANGJIN', 'XINGCHENG', 'ZUIDAML', 'ZUIDAGLZS', 'ZUIDANJZS', 'FADJTYJS', 'RANLIAOXS', 'RANYOUBH', 'GONGYOUFS', 'GANGGCL', 'GANGTCL', 'HUANBBZ', 'DANGWEIGS', 'BIANSUXIANGLX', 'JIANCHENG', 'QUDONGFS', 'SIQUXINGS', 'ZHONGYCSQJG', 'QIANXJLX', 'HOUXJLX', 'ZHULILX', 'CHETIJG', 'QIANZDQLX', 'HOUZDQLX', 'ZHUCZDLX', 'QIANLTGG', 'HOULTGG', 'BEITGG', 'ZHUFUJSZAQQL', 'QIANHOUPCQL', 'QIANHOUPTBQL', 'XIBUQL', 'TAIYAJCZZ', 'LINGTYJXXS', 'ANQDWXTS', 'ISOFINERTZYJK', 'ABSFANGBS', 'ZHIDLFP', 'SHACFZ', 'QIANYINLKZ', 'CHESHENWDKZ', 'BINGXFZ', 'CHEDPLYJXT', 'ZHUDSCZDAQXT', 'YESHIXT', 'PILJSTS', 'QIANHZCLD', 'DAOCESPYX', 'QUANJSXT', 'DINGSXH', 'ZISYXH', 'ZIDBCRW', 'FADJQTJS', 'SHANGPFZ', 'ZIDONGZC', 'DOUPOHJ', 'KEBXJ', 'KONGQXJ', 'DIANCGYXJ', 'KEBZXB', 'QIANQXHCSQ', 'ZHONGYCSQSZGN', 'HOUQXHCSQ', 'ZHENGTZDZXXT', 'DIANDTC', 'QUANJTC', 'YUNDWGTJ', 'LVHJLQ', 'DIANDXHM', 'CEHUAM', 'DIANDHBX', 'GANYHBX', 'CHEDXLJ', 'FADJDZFD', 'CHENZKS', 'YAOKYS', 'WUYSQDXT', 'WUYSJRXT', 'YUANCQD', 'PIZFXP', 'FANGXPTJ', 'FANGXPDDTJ', 'DUOGNFXP', 'FANGXPHD', 'FANGXPJR', 'FANGXPJY', 'XINGCDNXSP', 'QUANYJBP', 'HUDTAITSZXS', 'NEIZXCJLY', 'ZHUDJZ', 'SHOUJWXCD', 'ZUOYCZ', 'YUNDFGZY', 'ZUOYGDTJ', 'YAOBZCTJ', 'JIANBZCTJ', 'ZHUFJSZDDTJ', 'DIEPKBJDTJ', 'DIEPZYYD', 'HOUPZYDDTJ', 'FUJSWHPKTJAN', 'DIANDZYJY', 'QIANHPZYJR', 'QIANHPZYTF', 'QIANHPZYAM', 'DIEPDLZY', 'DISPZY', 'HOUPZYFDFS', 'QIANHZYFS', 'HOUPHJ', 'KEJRZLHJ', 'GPSDAOHXT', 'DAOLJYHJ', 'ZHONGKTCSDP', 'ZHONGKTCSDPCC', 'ZHONGKYJPFPXS', 'LANYCZDH', 'SHOUJHLYS', 'CHELW', 'CHEZDS', 'HOUPYJP', 'DIANYUAN', 'WAIJYYJK', 'CDDVD', 'YANGSQPP', 'YANGSQSL', 'JINGD', 'YUANGD', 'LEDRIJXCD', 'ZISYYJG', 'ZIZTD', 'ZHUANGXFZD', 'ZHUANXTD', 'QIANWD', 'DADGDKT', 'DADQXZZ', 'CHENFWD', 'QIANHDDCC', 'CHECYJSJ', 'CHECFJSGN', 'FANGZWXGRBL', 'HOUSJDDTJ', 'HOUSJJR', 'NEIWHSJZDFXM', 'LIUMTCNHSJ', 'HOUSJDDZD', 'HOUSJJY', 'HOUFDZYL', 'HOUPCZYL', 'HOUPCYSBL', 'ZHEYBHZJ', 'HOUYS', 'GANYYS', 'KONGTKZFS', 'HOUPDLKT', 'HOUZCFK', 'WENDFQKZ', 'CHENKQTJ', 'CHEZKQJHQ', 'CHEZBX', 'COLOR1', 'COLOR2', 'COLOR3', 'COLOR4', 'COLOR5', 'COLOR6', 'COLOR7', 'COLOR8', 'COLOR9', 'COLOR10', 'DUOTC', 'SHOUJHLYSGN', 'SUOSHUCX', 'GONGXBCDXSLC', 'KUAICDLBFB', 'CHEXJY', 'CHEXINGHJ', 'HOUPAQDSQL', 'SHICEXHLC', 'KUAICSJ', 'MANCSJ', 'SHICEKCSJ', 'SHICEMCSJ', 'DIANJLX', 'CHEDBCFZXT', 'DADYSGB', 'CHUMSYDD', 'FANGZWXBL', 'WAIHSJGN', 'NEIHSJGN', 'KEJIARPSZ', 'CHENPMGLZB', 'FULZFSQ', 'CHENXFZZ', 'XINGLXVDYJK', 'USBJKSL', 'HOUPKZDMT', 'SHOUSKZ', 'YUYSBKZXT', 'DAOHLKXXXS', 'ZHONGKYJPCC', 'ZHONGKCSYJPM', 'HOUPZYDDFD', 'HOUPZYFDXS', 'HOUPXZB', 'DIEPZYTJ', 'FUZYTJFS', 'ZHUZYTJFS', 'DIANDKDTB', 'FANGXPCZ', 'ZHUDBHSJQGS', 'YAOSLX', 'WEIMBLDLKQ', 'DIANDHBXWZJY', 'LUNQCZ', 'TIANCLX', 'SHESGYXT', 'ZIDJSJS', 'XUNHXT', 'DAOCCCYJXT', 'JIASFZYX', 'DAOLJTBSSB', 'TAIYJCGN', 'BEIDXRBH', 'HOUPAQSQL', 'QIANPZYGN', 'GANYYSGN', 'JIASMSQH', 'CHECYJSJGN', 'YEJYBCC', 'DIANDJZGL', 'DIANDJZNJ', 'QIANDDJZDGL', 'QIANDDJZDNJ', 'HOUDDJZDGL', 'HOUDDJZDNJ', 'XITZHGL', 'XITZHNJ', 'QUDDJS', 'DIANJBJ', 'DIANCLX', 'GONGXBXHLC', 'DIANCRL', 'BAIGLHDL', 'DIANCZZB', 'KUAICDL', 'DIANDJ', 'CHENHJFWD', 'ZUOYBJ', 'HOUPZYGN', 'YANGSQPPMC', 'DUOCGYBL', 'CHECJTB', 'QIANDDYWMS', 'DENGGTEGN', 'XIANHCSQ', 'HUOXCC', 'ZUIDZZZL', 'DIANCCDSJ', 'HOUPCMKQFS']

     book = xlwt.Workbook() # 创建一个excel对象
     sheet = book.add_sheet('Sheet1',cell_overwrite_ok=True) # 添加一个sheet页
     for i in range(len(title)): # 循环列
         sheet.write(0,i,title[i]) # 将title数组中的字段写入到0行i列中
     x = 0
     for k,v in a.items(): #　循环字典
         x += 1
         print('line:',k,v)
         sheet.write(x,0,k) #　将line写入到第x行，第0列中
         sheet.write(x,1,v) #　将line写入到第x行，第0列中

     book.save('demo.xls')

if __name__ == '__main__':
    writeM()